### ISSUE TITLE
header parsing in fasta.py requires string after accession

### ISSUE THREAD

**Issue by davidlevybooth** [hallamlab/TreeSAPP#31]
When creating a package with only refseq accensions in fasta header, an error is returned by fasta.py: "Unable to parse header." This can be traced back to the assumption in the regex to determine header format that accensions will be followed by a space then an additional string. Would it be possible to adjust the header parser to take headers with only accensions (i.e., '>EPS93299.1') as input? Thanks.

**Comment by cmorganl** [comment]
What version of TreeSAPP are you running? You can get this by running `treesapp info`.
I do have an 'accession_only' regular expression in fasta.py that matches ''>EPS93299.1''.

Unfortunately headers are not always consistently formatted so get_header_format occassionally breaks. Don't hesistate to notify me of headers that break it! I'm looking for a better way to parse these that is still easy for users that are not shell-savvy but more dependable than my array of regexes.
