### ISSUE TITLE
RPKM is not compiled during installation

### ISSUE THREAD

**Issue by cmorganl** [hallamlab/TreeSAPP#43]
The `rpkm` C++ code is not compiled during installation. We are going to be replacing this executable with a new Python package called `samsum` that we are developing in the Hallam lab. There are two main advantages to using a python package: ease of installation and an API.

When `samsum` is pushed to PyPI, we will include it in the requirements.txt file and it will be automatically installed during TreeSAPP installation with `pip`.

Having access to the API will allow us to call commands directly, preventing unnecessary I/O tasks and improve overall efficiency.

**Comment by davidlevybooth** [comment]
Related to this: When I run treesapp even without the --rpkm flag I get the following error: 
ERROR:root:Could not find a valid executable for rpkm.

As such I am unable to run the current version of treesapp. Is there a way to avoid this? 

Command: 
$treesapp assign -i <in.faa> -m prot -c meta -n 8 -o <out_dir>

**Comment by cmorganl** [comment]
Ah! I didn't realize you wouldn't be able to run treesapp at all without the rpkm executable. Thanks for bringing this to my attention. 
We're just working out some kinks in the [`samsum`](https://github.com/hallamlab/samsum) package  currently but I'll make a patch for the meantime. I'll update the thread when its ready.

**Comment by cmorganl** [comment]
Alright, I edited the Makefile used for compiling the `rpkm` code and introduced a new step to the README: `make rpkm` before `python setup.py install`. 

Let me know if it doesn't work. Thanks!

**Comment by cmorganl** [comment]
[samsum](https://pypi.org/project/samsum/) has now replaced the `rpkm` executable and a Makefile no longer exists.
