### ISSUE TITLE
Help page for "treesapp assign" lists usage as "treesapp ..." instead of "treesapp assign ..."

### ISSUE THREAD

**Issue by stephan-koenig** [hallamlab/TreeSAPP#47]

**Comment by cmorganl** [comment]
Issue was fixed in a recent commit ([a6ef902](https://github.com/hallamlab/TreeSAPP/commit/a6ef9023a7578dc9408ecbf26691b1993df67fb9)) to the ng-update branch.

Thanks for reporting that!
