### ISSUE TITLE
Installation of RefPkgs

### ISSUE THREAD

**Issue by bharat1912** [hallamlab/TreeSAPP#50]
Hi
I have installed treesapp successfully but am having problems installing the Refpkgs. I have used the following route.

$conda activate treesapp
$git clone https://github.com/hallamlab/RefPkgs.git
$cd RefPkgs
$./refpkg_manager.py -l

However, I get the following error:
Traceback (most recent call last):
  File "./refpkg_manager.py", line 12, in <module>
    from treesapp import refpkg as ts_refpkg
ImportError: cannot import name 'refpkg'

Any assistance gratefully accepted.

Bharat

**Comment by cmorganl** [comment]
Hi Bharat,

Sorry, for any confusion! I'm currently preparing for the next major version release and so some of the documentation relates to that version. The current release available from Conda and PyPI (v0.6.8) lack the code supporting RefPkgs, which hosts reference packages in a format that is entirely incompatible with versions <0.8.0.

Once the next version is released and propagated to Conda and PyPI you should be able to use RefPkgs as intended. I'm waiting for a dependency (pyfastx) to release their next version that contains a required feature before releasing the next version of TreeSAPP (hopefully next week!).

If you want to begin analyzing your data immediately you will need to either use the reference packages that come with the current version, or install TreeSAPP from  the 'ng_update' branch.

Let me know if you want a hand with anything!

Connor

**Comment by bharat1912** [comment]
> Hi
> I have installed treesapp successfully but am having problems installing the Refpkgs. I have used the following route.
> 
> $conda activate treesapp
> $git clone https://github.com/hallamlab/RefPkgs.git
> $cd RefPkgs
> $./refpkg_manager.py -l
> 
> However, I get the following error:
> Traceback (most recent call last):
> File "./refpkg_manager.py", line 12, in
> from treesapp import refpkg as ts_refpkg
> ImportError: cannot import name 'refpkg'
> 
> Any assistance gratefully accepted.
> 
> Bharat

**Comment by bharat1912** [comment]
Hi Connor
I have installed treesapp version 0.8.9 and wanted to integrate the database  from RefSeq into treesapp. For example,  /RefPkgs/Hydrocarbons/PHA_degradation/PETases.fasta. However, there is no .pkl file with this package so does this mean that I will need to create and integrate to treeapps/data

thanks
Bharat

**Comment by cmorganl** [comment]
Hi Bharat,

Sorry for not following up here more quickly. Yes, those that don't have a pkl file will need to be built with `treesapp create`. However, there is a pkl file for PHAdeg in Hydrocarbons/PHA_degradation/PHA_depolymerases/final_outputs/.

After building the refpkgs you're interested in either copy it into an existing installation directory using
```
./refpkg_manager.py --copy -n PHAdeg --treesapp_install /path/to/treesapp_venv/lib/python3.7/site-packages/treesapp/data/
```

or another directory where you're keeping reference packages (by changing the '--treesapp_install' path) you plan to use in your analysis.

I encourage you to also contribute reference packages to this repository by following our guidelines for [contributing](https://github.com/hallamlab/RefPkgs/blob/master/CONTRIBUTING.md)!

Connor
