### ISSUE TITLE
File `gtdbtk.ar122.summary.tsv` not found

### ISSUE THREAD

**Issue by stephan-koenig** [hallamlab/TreeSAPP#75]
As part of [Integrating MAGs and SAGs in reference packages tutorial](https://github.com/hallamlab/TreeSAPP/wiki/Integrating-MAGs-and-SAGs-in-reference-packages), you are supposed to download `gtdbtk.ar122.summary.tsv` but the [path](https://raw.githubusercontent.com/hallamlab/TreeSAPP/master/docs/gtdbtk.ar122.summary.tsv)  is incorrect and the file does not seem to be located on the TreeSAPP repo.

**Comment by cmorganl** [comment]
Should be fixed now. Thanks!
